// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndVfAGSVltWtdKjsp40yzdXKKTqrbDss',
    appId: '1:550264739666:android:8d14c44e68dc0795d8cc8b',
    messagingSenderId: '550264739666',
    projectId: 'wolly-1133d',
    storageBucket: 'wolly-1133d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdjkGGEeQBH87gPkhkXvfN2Ds__r9_H4g',
    appId: '1:550264739666:ios:7c040cd019869d0fd8cc8b',
    messagingSenderId: '550264739666',
    projectId: 'wolly-1133d',
    storageBucket: 'wolly-1133d.appspot.com',
    iosBundleId: 'com.example.wolly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Y5LE3kfuv14Viz7pzcSbEZhdySOUbcM',
    appId: '1:550264739666:web:889ef63529c127a1d8cc8b',
    messagingSenderId: '550264739666',
    projectId: 'wolly-1133d',
    authDomain: 'wolly-1133d.firebaseapp.com',
    storageBucket: 'wolly-1133d.appspot.com',
    measurementId: 'G-8VGN263DL3',
  );

}